{{- if include "rtsp-sftp-uploader.createSecret" . }}
{{- if or .Values.rtsp.url .Values.rtsp.password .Values.sftp.url .Values.sftp.password .Values.sftp.privateKey .Values.sftp.privateKeyPassphrase .Values.sftp.knownHosts }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rtsp-sftp-uploader.fullname" . }}
  labels:
    {{- include "rtsp-sftp-uploader.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.rtsp.url }}
  RTSP_URL: {{ . | quote }}
  {{- end }}
  {{- with .Values.rtsp.password }}
  RTSP_PASSWORD: {{ . | quote }}
  {{- end }}
  {{- with .Values.sftp.url }}
  SFTP_URL: {{ . | quote }}
  {{- end }}
  {{- with .Values.sftp.password }}
  SFTP_PASSWORD: {{ . | quote }}
  {{- end }}
  {{- with .Values.sftp.privateKeyPassphrase }}
  SFTP_PRIVATE_KEY_PASSPHRASE: {{ . | quote }}
  {{- end }}
  {{- with .Values.sftp.privateKey }}
  id: |
    {{- . | nindent 4 }}
  {{- end }}
  {{- with .Values.sftp.knownHosts }}
  known_hosts: |
    {{- . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
