{{- if and .Values.service.enabled .Values.http.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rtsp-sftp-uploader.fullname" . }}
  labels:
    {{- include "rtsp-sftp-uploader.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "rtsp-sftp-uploader.selectorLabels" . | nindent 4 }}
{{- end }}
